name: Build and delpoy thesis

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.SSH_KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: ''
        src: 'latex/thesis.pdf'
        dest: ${{secrets.SSH_PATH}}

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
